### ISSUE TITLE
Error in datapack 

### ISSUE THREAD

**Issue by LadySunx** [Xires87/FrycMod#2]
Modpack: Medieval MC [FABRIC] - MMC1 1.19.2

I added this mod to a modpack I am playing and below is the error message I get when trying to load into my world. 

"Erros in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("Safe mode"), or back to the title screen and fix it manually." 

**Note: When adding the single mods, I did make sure Frycmod was disabled while testing**

 Now I don't know if this helps or not, but I decided to slowly add each of your mods individually and launching the game to see which mod from the  FrycMod it could be. Well, everything turned out great by adding them individually so there's no problems with the individual mods themselves when loading into the world but if you were to use the Frycmod it comes with that error when trying to load into the world.

**Comment by Xires87** [comment]
Hi!
Thank you for testing, it really helped me find the problem.
Fix is already on Curseforge (Frycmod - 1.3.7)
